-- -- drop table
DROP TABLE IF EXISTS RESERVATION;

-- create table
CREATE TABLE RESERVATION (
    ID          INT NOT NULL AUTO_INCREMENT,
    GATE_ID     INT NOT NULL
	    CONSTRAINT RESERVATIONS_GATE_ID_FK
	    REFERENCES GATE
	    ON DELETE CASCADE,
    TIME_FROM   DATETIME NOT NULL,
    TIME_TO     DATETIME NOT NULL,
    PRIMARY KEY(ID)
);
