-- inserting configurations

INSERT INTO FLIGHT (ID, NAME) VALUES (1, 'flight01');
INSERT INTO FLIGHT (NAME) VALUES ('flight02');
INSERT INTO FLIGHT (NAME) VALUES ('flight03');

INSERT INTO GATE (ID, NAME, FLIGHT_ID, STATUS) VALUES (1, 'gate01', 1, 'RESERVED');
INSERT INTO GATE (NAME) VALUES ('gate02');
INSERT INTO GATE (NAME) VALUES ('gate03');





