-- drop tables
DROP TABLE IF EXISTS FLIGHT;
DROP TABLE IF EXISTS GATE;

CREATE TABLE FLIGHT (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) UNIQUE,
    PRIMARY KEY(ID)
);

-- create tables
CREATE TABLE GATE (
    ID INT NOT NULL AUTO_INCREMENT,
    FLIGHT_ID INT UNIQUE,
    NAME VARCHAR(30) NOT NULL UNIQUE,
    STATUS VARCHAR(20) DEFAULT 'OPENED', -- OPENED, RESERVED, CLOSED
    PRIMARY KEY(ID),
    CONSTRAINT GATE_FLIGHT_ID_FK
        FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID)
);
